Added a Twitter timeline and a YouTube video embed.
TeamSTEP/witch-one-homepage pull request #71
Opened 2021-11-20 09:58 UTC by psiwray

The Twitter timeline can be found at the bottom of the page, right after the last section and before the footer. The YouTube embed is instead found below the preorder button.

Both the timeline and the video embed are responsive. The timeline is just centered around the screen, occupying the full width on the smaller ones. The video embed has rounded corners, so that it doesn't look too blocky. The video embed simply stretches horizontally to fill the section it's in. As the timeline, the video occupies the full width on the smaller screens.

2021-11-20 10:12 UTC, psiwray commented
The browser is also complaining about a DOM attribute, `allowFullscreen`, inside the `iframe`. It suggests to change it to the same name, which is weird. For now, it isn't causing problems, but it would be nice to get rid of that error.

2021-11-20 11:41 UTC, hoonsubin requested changes

2021-11-20 11:41 UTC, hoonsubin commented on package.json
> +    "@tailwindcss/aspect-ratio": "^0.3.0",
this should be a dev dependency

2021-11-20 11:41 UTC, hoonsubin commented on src/templates/YouTubeEmbed.tsx
> +const YouTubeEmbed = () => (
make this into a component with the prop `src: string` (video source), and optional prop of `height` and `width`.
The actual prop and behavior may change depending on how it works on the page, but we want the embedded video to be a reusable component

2021-11-20 15:54 UTC, hoonsubin requested changes
sorry for missing this point on my previous review

2021-11-20 15:54 UTC, hoonsubin commented on src/templates/TwitterTimeline.tsx
> +const TwitterTimeline = () => (
I should have added this on my previous review, but looks like I forgot to do it.
Can you change this as a reusable component too like the YouTube component? The `screenName`, `width`, `height` should be passed as a prop.

2021-11-20 15:54 UTC, hoonsubin commented on src/templates/Base.tsx
> +    <TwitterTimeline />
We should have a new section called `SocialMedia` with a header saying `Social Media` and show the Twitter timeline. We will be adding more social medial feeds later.

2021-11-22 08:42 UTC, hoonsubin requested changes

2021-11-22 08:42 UTC, hoonsubin commented on src/templates/TwitterTimeline.tsx
> +  sourceType: string;
The `sourceType` should have the type of `'url' | 'profile' | 'list'` based on the types listed on https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/scripting-factory-functions

2021-11-27 12:53 UTC, hoonsubin approved these changes
LGTM

2021-11-27 12:53 UTC, merged